services:
  - type: web
    name: meeting-vote
    runtime: node
    plan: 0.5c-512mb
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATA_DIR
        value: /opt/render/project/src/data
      - key: USE_POSTGRES
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: meeting-vote-db-v2
          property: connectionString
    disk:
      name: meeting-vote-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

databases:
  - name: meeting-vote-db-v2
    plan: 0.1c-256mb
    postgresMajorVersion: "14"
    diskSizeGB: 1
